server:
  port: 8080

spring:
  application:
    name: helloWorld

  datasource:
#    hello is database name
    url: jdbc:mysql://localhost:3306/helloWorld?user=root
    username: root
    password: springboot

mybatis:
#  Before executing, you need to scan XML files otherwise, they appear as errors when invoke
  mapper-locations:
    - classpath:/mapper/**/*.xml

count: 5
my:
  name: John