#H2 DB
server:
  port: 9100 # 伺服器的port號

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:todolist # h2 database 連接位址
    driver-class-name: org.h2.Driver # 配置driver
    username: root # database 用戶名
    password: springboot # database 密碼

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  thymeleaf:
    cache: false
    prefix: classpath:/templates/    # 設定去templates資料夾找html檔案
    suffix: .html
    encoding: UTF-8
    mode: HTML5

  messages:
    fallback-to-system-locale: false # 找不到當前語言檔時，至系統默認index.properties
    basename: static/lang/index # 將語言檔配置在static/lang底下，預設為index
    encoding: UTF-8

##MySQL
#server:
#  port: 8080
#
#spring:
#  application:
#    name: helloWorld
#
#  datasource:
##    hello is database name
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/hello?user=root
#    username: root
#    password: springboot
#
#  jackson:
#    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss
#
#mybatis:
##  Before executing, you need to scan XML files otherwise, they appear as errors when invoke
#  mapper-locations:
#    - classpath:/mapper/**/*.xml


count: 5
my:
  name: John