server:
  port: 8080

spring:
  application:
    name: helloWorld

  datasource:
#    hello is database name
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hello?user=root
    username: root
    password: springboot

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
#  Before executing, you need to scan XML files otherwise, they appear as errors when invoke
  mapper-locations:
    - classpath:/mapper/**/*.xml


count: 5
my:
  name: John